### PR TITLE
Bug fix + basic cleanup

### PR DESCRIPTION
**Pull request by imdfl**
* Replaced jQuery search for body with editor.editable().$
* Added <code>strict</code> mode
* removed global variables
* passed jQuery as a parameter

### CODE REVIEW

**Comment by andykirk** [comment]
Hi,

Thanks for all your work on this - I really appreciate it. It all looks good. Can you clarify which bug it fixes before I merge this?

Thanks,
Andy

**Comment by imdfl** [comment]
sure: 
1. the search for footnote elements used an explicit path containing an iframe, which fails when ckeditor is not embedded in one (e.g. when the divarea plugin is used). I changed it so the search would start at the ckeditor editable() element, which is always the correct dom element. I would forego jquery and use ckeditor's dom traversal methods, but since you prefer jquery, I have stuck with it.
2. there were several global variables in the code, exposed when I added the "use strict" directive. This was obviously not intentional so I just scoped the variables.

**Comment by andykirk** [comment]
Brilliant! Thanks.

I'm totally not opposed to using CKEditor DOM traversal methods at all - I just used jQuery out of familiarity and time constraints. Ideally I'd like to remove the dependency of jQuery entirely, but I'm not sure if CKEditor's methods are on a par with jQuery for all cases. At least - I struggled to find out how to do lots of stuff with CKE natively - which is why I turned to jQuery in the first place.

Cheers

**Comment by imdfl** [comment]
Fair enuf. I think that you can manage with the ckeditor api, but if you do choose to stick with jq, you need to verify that it's loaded or at least fail gracefully if it's not present.

**Comment by andykirk** [comment]
True. [sheepish look].
I'll look into that next because I think it'll take me a while remove JQ dep. 


Thanks again.

**Comment by andykirk** [comment]
I can't automatically merge this PR, so I've done it manually.
83cf540bcd14f38d1803a359a06337de12c868d5

**Pull request closed without merging**
